### ISSUE TITLE
Write contribution guide

### ISSUE THREAD

**Issue by geomC** [FixMyBerlin/fixmy.platform#253]
# TODOs
- [X] keep documents in feature branch: https://github.com/FixMyBerlin/fixmy.frontend/tree/docs/contribution_guide
- [x] write first draft of Contribution guide
- [x] Link contribution guide in README.md
- [x] compile Pull request template, see https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository for where this should go
- [x] use Issue templates? discuss this!
A decided to add a template within that PR which we can discuss during Review.

# Contents of Contribution guide
## Meta
- [x] A welcoming!
- [x] TOC
- [x] A little about the project and the core team
- [x] Short links to important resources -> READMEs
- [x] Contacts: Slack, email. Who/Where can someone ask for help?

## Get started
- [x] ~~How to set up the local dev environment~~
- [x] ~~How to run tests~~
- [x] ~~Architecture?~~ 
- [x] ~~Code Conventions not covered by eslint?~~

All this should be in the README.MD. Linking it does the job.

- [ ] Make sure the README states how to run tests.

## Issues
- [x] A little about the github group structure --> why we keep all issues (frontend and backend) in /platform
- [x] Why the german-english mix? Why are there very short, eventually cryptic issues? --> boundaries of time and budget
- [x] How should larger ideas should be aproached? --> talk to us first
- [x] How should Issues regarding smaller things (bug, enhancement) be opened?
- [x] How can issues suitable for external contribution be spotted?
- [x] ~~In what areas are we explicitly looking for external contributions? IMHO bugfixes, smaller features buried in the back log, testing~~ We should keep that in issues.

## PRs
- [x] ~~structure (only needed if we do not use a template)~~ Going for the PR template here.

# Sources
https://mozillascience.github.io/working-open-workshop/contributing/
https://github.com/nayafia/contributing-template
https://github.com/atom/atom/blob/master/CONTRIBUTING.md
https://embeddedartistry.com/blog/2017/08/04/a-github-pull-request-template-for-your-projects/

**Comment by ciex** [comment]
Closed by https://github.com/FixMyBerlin/fixmy.frontend/pull/308
