### ISSUE TITLE
Use dotenv for configuration

### ISSUE THREAD

**Issue by ciex** [FixMyBerlin/fixmy.platform#285]
**What's the problem you want solved?**

- There is no way to configure secrets
- There are a lot of commands in package.json just to run the same binaries with different environment variables

**Is there a solution you'd like to recommend?**

Configure dotenv so that 

**Tasks**

- [x] Step 1 Setup dotenv to replace Webpack.EnvironmentPlugin
- [x] Step 2 Replace some package.json commands with configuration options in .env file
- [x] Step 3 Clarify usage of options such as "CONFIG_ENV" where the name doesn't make clear what it is configuring
- [x] Step 4 Replace Cypress configuration option of secrets by setting secrets in .env files
