### ISSUE TITLE
Let report marker icon colors reflect their status

### ISSUE THREAD

**Issue by ciex** [FixMyBerlin/fixmy.platform#291]
**What's the problem you want solved?**

All markers are yellow (interaction color)

**Is there a solution you'd like to recommend?**

Let markers use colors as defined in https://app.zeplin.io/project/5ad5f75adf221b9343d45559/screen/5bf2f0179dcaf67e9557d93e

**Tasks**

- [ ] Create marker icons for each stage
- [ ] Let marker component receive information about associated status
- [ ] Update marker compnoent to use the appropriate marker icon

**Comment by ciex** [comment]
Duplicate of #282
