### ISSUE TITLE
Setup Eichwalde project

### ISSUE THREAD

**Issue by cafca** [FixMyBerlin/fixmy.platform#359]
**Tasks**

- [x] Add base config
- [ ] Configure menu
- [ ] Add page about research project
- [ ] Provision server instance and configure in app

**Comment by cafca** [comment]
Closed for inactivity
