### ISSUE TITLE
Migrate Matomo to Lightsail

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.platform#369]
**What's the problem you want solved?**
- Derzeit liegt Matomo auf meinem privaten Server

**Is there a solution you'd like to recommend?**
- Umzug auf einen Server in AWS Lightsail

**Tasks**
- [x] VM auf Lightsail erstellen
- [x] Matomo auf Lightsail installieren
- [x] Daten migrieren
- [x] Testen
- [x] URL umstellen
- [x] Testen
- [x] Altes Matomo löschen (Boris)

**Comment by ohrie** [comment]
This is done.
