### ISSUE TITLE
Let admins send offers to extend permit duration

### ISSUE THREAD

**Issue by ciex** [FixMyBerlin/fixmy.platform#402]
**What's the problem you want solved?**

Permits will run out on 8/31.

**Is there a solution you'd like to recommend?**

Let admins send offers to business owners to offer applying for a subsequent permit.

**Tasks**

- [x] Fix access_key on data model
- [x] Add admin action to send an E-Mail with a customized link to a confirmation page
- [x] Add data model field to record whether an offer for a subsequent permit has been sent
