### ISSUE TITLE
[Frontend] Replace fetch-mock with msw

### ISSUE THREAD

**Issue by s-pic** [FixMyBerlin/fixmy.platform#424]
# Story
Instead of specifically mocking fetch/axios/ky/whatever in our tests, we can use [msw ](https://github.com/mswjs/msw) to
intercept http requests and answer them with mock data **on network level** instead of application level. By making our tests agnostic to the http library issuing the request, we can easily replace that lib. Furthermore, msw can be used during development, e.g. to develop against an endpoint that does not exist yet.
See https://kentcdodds.com/blog/stop-mocking-fetch/ for a high level introduction to msw.

We introduced msw in https://github.com/FixMyBerlin/fixmy.frontend/pull/490, so we can use the existing setup.

# Subtask / Notes

- [ ] move msw setup from `jest/jest.setupAfterEnv.js` to extra file (as discussed with @ciex )
- [ ] warn on unhandled requests
- [] start with reports in order to target https://github.com/FixMyBerlin/fixmy.platform/issues/250

**Comment by cafca** [comment]
Related commits: 
https://github.com/FixMyBerlin/fixmy.frontend/commit/80122873645802bfa06388735a7091c4b1919a44
https://github.com/FixMyBerlin/fixmy.frontend/commit/27560b06a5bde718f9e83ac00d7c5a5a0c3a6402
