### ISSUE TITLE
Move reports to own Django application

### ISSUE THREAD

**Issue by cafca** [FixMyBerlin/fixmy.platform#440]
**What's the problem you want solved?**

The `fixmyapp` Django application has become convoluted with very long modules that are hard to maintain.

**Is there a solution you'd like to recommend?**

Move everything related to reports into its own *reports* django app

**Tasks**

- [x] Create new *reports* application
- [x] Migrate data from `fixmyapp.report` to `reports.report`
- [x] Deprecate `fixmyapp.report` and direct all endpoints to *reports* app
