### ISSUE TITLE
Harmonize report import and export formats

### ISSUE THREAD

**Issue by cafca** [FixMyBerlin/fixmy.platform#467]
**What's the problem you want solved?**

Import and export commands have different formats

**Is there a solution you'd like to recommend?**

Let them have the same format

**Tasks**

CSV export

- [x] Add columns: origin ids, url, 
- [x] split position column into long and lat columns
- [x] remove subject, photo column
- [x] Fix column contents for likes, created_date, modified_date

geojson export

- [x] Add columns: origin_ids, photo src

**Comment by cafca** [comment]
Duplicate of https://github.com/FixMyBerlin/fixmy.platform/issues/447
