### ISSUE TITLE
Create PDF Archive of Gastro Sign ups

### ISSUE THREAD

**Issue by ohrie** [FixMyBerlin/fixmy.platform#646]
**What's the problem you want solved?**
We want an export of all Gasto Signups and approvals in one or multiple PDFs. These PDFs act as an archive.

**Is there a solution you'd like to recommend?**
There was a solution in the previous years. But no solution known right now.

**Tasks**
- [x] Find out how to create PDF archive
- [x] Create PDF Archive for 2020 and 2021
- [x] Document how to create PDF Archive.

**Comment by ohrie** [comment]
Has now it's own repository: https://github.com/FixMyBerlin/GastroScript
